language: java
jdk:
- oraclejdk8
before_install:
- chmod +x mvnw
install: true
services:
- docker
script: ./mvnw clean install -Pbuild-resource -DskipTests=true -Dorg.revo.env.buckets.static.domainname=$cloudfront_domainname
#script: ./mvnw clean install docker:build docker:push -Pbuild-resource -DskipTests=true -Ddocker.username=$docker_username -Ddocker.password=$docker_password -Dorg.revo.env.buckets.static.domainname=$cloudfront_domainname
cache:
  directories:
  - $HOME/.m2
after_success:
- rm -r -f src/main/resources/ui-static/node
- rm -r -f src/main/resources/ui-static/node_modules
- rm -r -f target/!(*.jar)
- git add .
- git add -f src/main/resources/static/
- git commit -m "push $repo"
deploy:
- provider: s3
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  bucket: $s3_bucket_name
  region: us-east-1
  upload-dir: $repo
  acl: public_read
- provider: cloudfoundry
  username: $cloudfoundry_username
  password: $cloudfoundry_password
  api: https://api.run.pivotal.io
  organization: $cloudfoundry_organization
  space: development